export const SMASH_EGG_ASSETS = {
  bgRays: '/assets/smash-egg/bg-rays.png',
  bgGlow: '/assets/smash-egg/bg-glow.png',
  eggWhole: '/assets/smash-egg/egg-whole.png',
  eggCracked: '/assets/smash-egg/egg-cracked.png',
  nest: '/assets/smash-egg/nest.png',
  tokenIcon: '/assets/smash-egg/token-icon.svg',
  coinsIcon: '/assets/smash-egg/coins-icon.svg',
  termsIcon: '/assets/smash-egg/terms-icon.svg',
  backArrow: '/assets/smash-egg/back-arrow.svg',
  soundIcon: '/assets/smash-egg/sound-icon.png',
  menuIcon: '/assets/smash-egg/menu-icon.png',
  prizeSmartphone: '/assets/smash-egg/prize-smartphone.png',
  prizeSmartwatch: '/assets/smash-egg/prize-smartwatch.png',
  prizeEarbuds: '/assets/smash-egg/prize-earbuds.png',
  rankBadge1: '/assets/smash-egg/rank-badge-1.png',
  rankBadge2: '/assets/smash-egg/rank-badge-2.png',
  rankBadge3: '/assets/smash-egg/rank-badge-3.png',
};
