export const BASE_URL = process.env.NEXT_PUBLIC_BASEURL || 'https://staging-api.kinggroup44.com';

export const ENDPOINTS = {
  MEMBER: {
    GENERATE_TOKEN: '/login/generate-token/',
    CHECK_IN: '/member/members/check-in/',
    WELCOME_GIFT: '/member/members/welcome/',
    MEMBER_INFO: (uuid) => `/member/members/${uuid}/`,
    MEMBER_TOKENS: (uuid) => `/member/${uuid}/member-tokens/`,
    MEMBER_REWARDS: (uuid) => `/member/${uuid}/member-rewards/`,
    KICK: (uuid) => `/member/${uuid}/kick/`,
    KICK_HISTORY: (uuid) => `/member/${uuid}/kick-history/`,
    KICK_FULL_HISTORY: (uuid) => `/member/${uuid}/kick-full-history/`,
    KICK_REDEEM_ALL: (uuid) => `/member/${uuid}/kick/redeem-all/`,
    PENALTY_KICK_GAME_STATUS: '/penalty-kick/game-status/',
    ONE_SPIN: (uuid) => `/member/${uuid}/one-spin/`,
    TEN_SPIN: (uuid) => `/member/${uuid}/ten-spin/`,
    FIFTY_SPIN: (uuid) => `/member/${uuid}/fifty-spin/`,
    HUNDRED_SPIN: (uuid) => `/member/${uuid}/hundred-spin/`,
    PROFILE: (uuid) => `/member/profile/${uuid}/`,
    UPDATE_PROFILE: (uuid) => `/member/profile/${uuid}/update-profile/`,
    ALL_LUCKY_SPIN_ITEMS: '/lucky-spin/lucky-spin-items/',
    ALL_REDEMPTION_ITEMS: '/redemption/redemption-items/',
    AVAILABLE_REDEMPTION_ITEMS: '/redemption/redemption-items/available-items/',
    REDEEM_ITEM: (uuid) => `/redemption/redemption-items/${uuid}/redeem/`
  },
  FRONT_VIEW: {
    WINNING_LIST: '/front-view/winning-list/',
    TOTAL_USERS: '/front-view/total-users/',
    ACTIVE_USERS: '/front-view/active-users/',
    DAILY_CHECK_IN: '/front-view/daily-check-in/',
    FEATURE_STATUS: '/front-view/feature-status/'
  },
  SETTINGS: {
    PUBLIC_BANNERS: '/settings/banners/public/'
  },
  MISSION: {
    MISSIONS: '/mission/missions/',
    MISSION: (uuid) => `/mission/missions/${uuid}/`,
    ARCHIVE: (uuid) => `/mission/missions/${uuid}/archive/`,
    MY_MISSIONS: '/mission/missions/my-missions/',
    JOIN: (uuid) => `/mission/missions/${uuid}/join/`,
    CLAIM: (uuid) => `/mission/missions/${uuid}/claim/`,
    PROGRESS_HISTORY: '/mission/missions/progress-history/',
  },
  ADMIN: {
    // Previous admin login API:
    // LOGIN: '/login/admin-access-token/',
    LOGIN: '/login/admin-login/',
    LOGIN_COMPLETE: '/login/admin-login/complete/',
    LOGOUT: '/login/logout/',
    REFRESH_TOKEN: '/login/refresh-token/',
    VERIFY_TOKEN: '/login/verify-token/',
    USERS: '/admins/users/',
    USER_SINGLE: (uuid) => `/admins/users/${uuid}/`,
    LOGIN_REQUESTS: '/admins/login-requests/',
    LOGIN_REQUEST_APPROVE: (uuid) => `/admins/login-requests/${uuid}/approve/`,
    LOGIN_REQUEST_REJECT: (uuid) => `/admins/login-requests/${uuid}/reject/`,
    ACTIVITY_LOG: '/admins/activity-log/',
    PERMISSIONS: '/admins/permissions/',
    ROLES: '/admins/roles/',
    ROLE_SINGLE: (uuid) => `/admins/roles/${uuid}/`,
    ROLE_ARCHIVE: (uuid) => `/admins/roles/${uuid}/archive/`,
    VIP_TIERS: '/member/vip-tier/',
    VIP_TIER: (uuid) => `/member/vip-tier/${uuid}/`,
    ARCHIVE_VIP_TIER: (uuid) => `/member/vip-tier/${uuid}/archive/`,
    LUCKY_SPIN_ITEMS: '/lucky-spin/lucky-spin-items/',
    LUCKY_SPIN_ITEM: (uuid) => `/lucky-spin/lucky-spin-items/${uuid}/`,
    ARCHIVE_LUCKY_SPIN_ITEM: (uuid) => `/lucky-spin/lucky-spin-items/${uuid}/archive/`,
    LUCKY_SPIN_SEQUENCES: '/lucky-spin/lucky-spin-sequences/',
    LUCKY_SPIN_SEQUENCE: (uuid) => `/lucky-spin/lucky-spin-sequences/${uuid}/`,
    CHANGE_SPIN_SEQUENCES: '/lucky-spin/lucky-spin-sequences/change-spin-sequences/',
    MEMBERS: '/member/members/',
    TOKEN_REPORT: '/member/token-report/',
    REWARD_REPORT: '/member/reward-report/',
    MEMBER_LIST: '/member/member-list/',
    MEMBER_LIST_SINGLE: (uuid) => `/member/member-list/${uuid}/`,
    MEMBER_DEPOSIT: (uuid) => `/member/${uuid}/member-deposit/`,
    REDEMPTION_ITEMS: '/redemption/redemption-items/',
    REDEMPTION_ITEM: (uuid) => `/redemption/redemption-items/${uuid}/`,
    ARCHIVE_REDEMPTION_ITEM: (uuid) => `/redemption/redemption-items/${uuid}/archive/`,
    CHECKIN_SETTINGS: '/settings/checkin-settings/',
    BANNERS: '/settings/banners/',
    BANNER: (uuid) => `/settings/banners/${uuid}/`,
    ARCHIVE_BANNER: (uuid) => `/settings/banners/${uuid}/archive/`,
    MEMBER_REPORT_DAILY: '/member/member-report/daily/',
    MEMBER_REPORT_MONTHLY: '/member/member-report/monthly/',
    MEMBER_REPORT_YEARLY: '/member/member-report/yearly/',
    STATION_LIST: '/front-view/station-list/',
    REDEMPTION_TIERS: '/redemption/redemption-tier/',
    REDEMPTION_TIER_SINGLE: (uuid) => `/redemption/redemption-tier/${uuid}/`,
    ARCHIVE_REDEMPTION_TIER: (uuid) => `/redemption/redemption-tier/${uuid}/archive/`,
    CHECKIN_TIER: '/settings/check-in-tier/',
    WALLET_VIP: '/third-party/wallet-vip/',
    WALLET_VIP_SINGLE: (uuid) => `/third-party/wallet-vip/${uuid}/`,
    WALLET_VIP_ARCHIVE: (uuid) => `/third-party/wallet-vip/${uuid}/archive/`,
    FLOATING_MENU: '/third-party/floating-menu/',
    FLOATING_MENU_SINGLE: (uuid) => `/third-party/floating-menu/${uuid}/`,
    FLOATING_MENU_ARCHIVE: (uuid) => `/third-party/floating-menu/${uuid}/archive/`,
    FLOATING_MENU_ROOT_ICON: '/third-party/floating-menu-root-icon/',
    FRAMES: '/third-party/frame/',
    FRAME_SINGLE: (uuid) => `/third-party/frame/${uuid}/`,
    FRAME_ARCHIVE: (uuid) => `/third-party/frame/${uuid}/archive/`,
    PENALTY_KICK_SETTINGS: '/penalty-kick/penalty-kick-settings/',
    PENALTY_KICK_ITEMS: '/penalty-kick/penalty-kick-items/',
    PENALTY_KICK_ITEM: (uuid) => `/penalty-kick/penalty-kick-items/${uuid}/`,
    PENALTY_KICK_ITEM_ARCHIVE: (uuid) => `/penalty-kick/penalty-kick-items/${uuid}/archive/`,
    PENALTY_KICK_SEQUENCES: '/penalty-kick/kick-sequences/',
    PENALTY_KICK_SEQUENCE: (uuid) => `/penalty-kick/kick-sequences/${uuid}/`,
    PENALTY_KICK_SEQUENCE_REORDER: '/penalty-kick/kick-sequences/change-kick-sequences/',
    AVAILABLE_PROMOTIONS: '/settings/available-promotions/',
    PROMOTIONS: '/settings/promotions/',
    PROMOTIONS_BY_STATION: (stationUuid) => `/settings/promotions/get-by-station/${stationUuid}/`,
    MISSION_SETTINGS: '/mission/settings/'
  },
  EXTERNAL: {
    SPECIAL_CODE: '/third-party/special-codes/',
    WALLET_VIP_TIERS: (specialCode) => `/third-party/station-wallet-vip/${specialCode}/`,
    FLOATING_MENUS: (specialCode) => `/third-party/station-floating-menu/${specialCode}/`
  },
  WORLDCUP_USER: {
    COUNTRY_LIST: '/worldcup/country-list/',
    MATCH_COUNTRY_LIST: '/worldcup/match-country-list/',
    INFO: '/worldcup/info/',
    BANNER_LIST: '/worldcup/banner-list/',
    PRIZE_POOL: '/worldcup/prize-pool/',
    PRIZE_POOL_SINGLE: (uuid) => `/worldcup/prize-pool/${uuid}/`,
    LEADERBOARD_COUNTRIES: '/worldcup/leaderboard/countries/',
    LEADERBOARD_PLAYERS: '/worldcup/leaderboard/players/',
    LEADERBOARD_TOP_PER_COUNTRY: '/worldcup/leaderboard/top-per-country/',
    MATCH_LIST: '/worldcup/match-list/',
    MATCH_LIST_SINGLE: (uuid) => `/worldcup/match-list/${uuid}/`,
    PROFILE: (uuid) => `/worldcup/${uuid}/profile/`,
    CHOOSE_COUNTRY: (uuid) => `/worldcup/${uuid}/choose-country/`,
    PREDICT: (uuid) => `/worldcup/${uuid}/predict/`,
    PREDICTIONS: (uuid) => `/worldcup/${uuid}/predictions/`,
    MATCH_PREDICTIONS: (uuid) => `/worldcup/${uuid}/match-predictions/`,
    PREDICTION_STATUS: (uuid) => `/worldcup/${uuid}/prediction-status/`,
    MY_PREDICTION: (memberUuid, matchUuid) => `/worldcup/${memberUuid}/matches/${matchUuid}/my-prediction/`,
  },
  WORLDCUP_ADMIN: {
    SETTINGS: '/worldcup/settings/',
    BANNERS: '/worldcup/banners/',
    BANNER: (uuid) => `/worldcup/banners/${uuid}/`,
    BANNER_ARCHIVE: (uuid) => `/worldcup/banners/${uuid}/archive/`,
    REWARD_ITEMS: '/worldcup/reward-items/',
    REWARD_ITEM: (uuid) => `/worldcup/reward-items/${uuid}/`,
    REWARD_ITEM_ARCHIVE: (uuid) => `/worldcup/reward-items/${uuid}/archive/`,
    MATCHES: '/worldcup/matches/',
    MATCH: (uuid) => `/worldcup/matches/${uuid}/`,
    MATCH_ARCHIVE: (uuid) => `/worldcup/matches/${uuid}/archive/`,
    MATCH_SETTLE: (uuid) => `/worldcup/matches/${uuid}/settle/`,
    DUMMY_PLAYERS: '/worldcup/dummy-players/',
    DUMMY_PLAYER: (uuid) => `/worldcup/dummy-players/${uuid}/`,
    DUMMY_PLAYER_ARCHIVE: (uuid) => `/worldcup/dummy-players/${uuid}/archive/`,
    DUMMY_COUNTRIES: '/worldcup/dummy-countries/',
    DUMMY_COUNTRY: (uuid) => `/worldcup/dummy-countries/${uuid}/`,
    DUMMY_COUNTRY_ARCHIVE: (uuid) => `/worldcup/dummy-countries/${uuid}/archive/`,
    RANKING_REALTIME: '/worldcup/ranking/realtime/',
    DASHBOARD_KPI: '/worldcup/dashboard/kpi/',
  },
  CRM: {
    // User Access Panel
    USERS: '/admins/users/',
    USER_SINGLE: (uuid) => `/admins/users/${uuid}/`,
    LOGIN_REQUESTS: '/admins/login-requests/',
    LOGIN_REQUEST_APPROVE: (uuid) => `/admins/login-requests/${uuid}/approve/`,
    LOGIN_REQUEST_REJECT: (uuid) => `/admins/login-requests/${uuid}/reject/`,
    ACTIVITY_LOG: '/admins/activity-log/',
    PERMISSIONS: '/admins/permissions/',
    ROLES: '/admins/roles/',
    ROLE_SINGLE: (uuid) => `/admins/roles/${uuid}/`,
    ROLE_ARCHIVE: (uuid) => `/admins/roles/${uuid}/archive/`,
    // Member Profile
    MEMBERS: '/crm-members/members/',
    MEMBER_SINGLE: (uuid) => `/crm-members/members/${uuid}/`,
    MEMBER_REFRESH: (uuid) => `/crm-members/${uuid}/refresh/`,
    MEMBER_UPDATE_DATA: (uuid) => `/crm-members/${uuid}/update-data/`,
    // Retention Alert System
    PRIORITY_SUMMARY: '/crm-members/priority-summary/',
    REFRESH_MEMBERS: '/crm-members/refresh-members/',
    // Retention Profile
    RETENTION_SUMMARY: (adminUuid) => `/crm-members/retention-summary/${adminUuid}/`,
    // Old path returned 404 on staging:
    // RETENTION_MEMBERS: '/crm-members/retention-profile/',
    RETENTION_MEMBERS: '/crm-members/retention-members/',
    ADMIN_MEMBERS: (adminUuid) => `/crm-members/${adminUuid}/admin-members/`,
    FOLLOW_UPS: '/crm-members/follow-up/',
    MEMBER_ASSIGN_TO_PIC: (memberUuid) => `/crm-members/members/${memberUuid}/assign-to-pic/`,
    MEMBER_FOLLOW_UP: (memberUuid) => `/crm-members/members/${memberUuid}/follow-up/`,
    MEMBER_ALERT: (memberUuid) => `/crm-members/members/${memberUuid}/alert/`,
    MEMBER_SEND_BONUS: (memberUuid) => `/crm-members/members/${memberUuid}/send-bonus/`,
    // Dashboard
    DASHBOARD_SUMMARY: '/crm-admins/dashboard-summary/',
    DASHBOARD_BREAKDOWN: '/crm-admins/dashboard-breakdown/',
    DASHBOARD_DETAILS: '/crm-admins/dashboard-details/',
    NOTIFICATIONS: '/crm-admins/notifications/',
    NOTIFICATION_MARK_READ: (uuid) => `/crm-admins/notifications/${uuid}/mark-as-read/`,
    // Member Assignment
    ASSIGNMENTS: '/crm-admins/assignments/',
    ASSIGNMENT_SINGLE: (uuid) => `/crm-admins/assignments/${uuid}/`,
    ASSIGNMENT_IMPORT_MEMBERS: (uuid) => `/crm-admins/assignments/${uuid}/import-members/`,
    ASSIGNMENT_RETENTION_TARGET: (adminUuid) => `/crm-admins/assignments/${adminUuid}/retention-target/`,
    ASSIGNMENT_SET_TARGET: '/crm-admins/assignments/set-target/',
    // CRM MRS VIP Tier aliases.
    // Old CRM-specific paths returned 404 on staging:
    // CRM_VIP_TIERS: '/crm-admins/vip-tier/',
    // CRM_VIP_TIER_SINGLE: (uuid) => `/crm-admins/vip-tier/${uuid}/`,
    // CRM_VIP_TIER_ARCHIVE: (uuid) => `/crm-admins/vip-tier/${uuid}/archive/`
    CRM_VIP_TIERS: '/member/vip-tier/',
    CRM_VIP_TIER_SINGLE: (uuid) => `/member/vip-tier/${uuid}/`,
    CRM_VIP_TIER_ARCHIVE: (uuid) => `/member/vip-tier/${uuid}/archive/`
  }
};
