export const BASE_URL = process.env.NEXT_PUBLIC_BASEURL || 'https://staging-api.kinggroup44.com';

export const ENDPOINTS = {
  MEMBER: {
    GENERATE_TOKEN: '/login/generate-token/',
    CHECK_IN: '/member/members/check-in/',
    WELCOME_GIFT: '/member/members/welcome/',
    MEMBER_INFO: (uuid) => `/member/members/${uuid}/`,
    MEMBER_TOKENS: (uuid) => `/member/${uuid}/member-tokens/`,
    MEMBER_REWARDS: (uuid) => `/member/${uuid}/member-rewards/`,
    KICK: (uuid) => `/member/${uuid}/kick/`,
    KICK_HISTORY: (uuid) => `/member/${uuid}/kick-history/`,
    KICK_FULL_HISTORY: (uuid) => `/member/${uuid}/kick-full-history/`,
    KICK_REDEEM_ALL: (uuid) => `/member/${uuid}/kick/redeem-all/`,
    PENALTY_KICK_GAME_STATUS: '/penalty-kick/game-status/',
    ONE_SPIN: (uuid) => `/member/${uuid}/one-spin/`,
    TEN_SPIN: (uuid) => `/member/${uuid}/ten-spin/`,
    FIFTY_SPIN: (uuid) => `/member/${uuid}/fifty-spin/`,
    HUNDRED_SPIN: (uuid) => `/member/${uuid}/hundred-spin/`,
    PROFILE: (uuid) => `/member/profile/${uuid}/`,
    UPDATE_PROFILE: (uuid) => `/member/profile/${uuid}/update-profile/`,
    ALL_LUCKY_SPIN_ITEMS: '/lucky-spin/lucky-spin-items/',
    ALL_SMASH_EGG_ITEMS: '/smash-egg/smash-egg-items/',
    ALL_SMASH_EGG_SEQUENCES: '/smash-egg/smash-sequences/',
    SMASH_EGG_SETTINGS: '/smash-egg/smash-egg-settings/',
    SMASH_EGG_WINNING_LIST: '/smash-egg/winning-list/',
    SMASH_EGG_HISTORY: (uuid) => `/member/${uuid}/smash-history/`,
    ONE_SMASH: (uuid) => `/member/${uuid}/one-smash/`,
    TEN_SMASH: (uuid) => `/member/${uuid}/ten-smash/`,
    FIFTY_SMASH: (uuid) => `/member/${uuid}/fifty-smash/`,
    HUNDRED_SMASH: (uuid) => `/member/${uuid}/hundred-smash/`,
    ALL_REDEMPTION_ITEMS: '/redemption/redemption-items/',
    AVAILABLE_REDEMPTION_ITEMS: '/redemption/redemption-items/available-items/',
    REDEMPTION_GAME_STATUS: '/redemption/game-status/',
    REDEEM_ITEM: (uuid) => `/redemption/redemption-items/${uuid}/redeem/`,
    // Redeem links (shared campaign URLs). INFO is public — no auth — so a
    // logged-out visitor can still be shown what the link is offering.
    REDEEM_LINK_INFO: (uuid) => `/redemption/redeem-link/${uuid}/info/`,
    REDEEM_LINK_CLAIM: (memberUuid, uuid) => `/redemption/${memberUuid}/redeem-link/${uuid}/redeem/`
  },
  FRONT_VIEW: {
    WINNING_LIST: '/front-view/winning-list/',
    TOTAL_USERS: '/front-view/total-users/',
    ACTIVE_USERS: '/front-view/active-users/',
    DAILY_CHECK_IN: '/front-view/daily-check-in/',
    FEATURE_STATUS: '/front-view/feature-status/'
  },
  SETTINGS: {
    PUBLIC_BANNERS: '/settings/banners/public/'
  },
  MISSION: {
    MISSIONS: '/mission/missions/',
    MISSION: (uuid) => `/mission/missions/${uuid}/`,
    ARCHIVE: (uuid) => `/mission/missions/${uuid}/archive/`,
    MY_MISSIONS: '/mission/missions/my-missions/',
    JOIN: (uuid) => `/mission/missions/${uuid}/join/`,
    CLAIM: (uuid) => `/mission/missions/${uuid}/claim/`,
    PROGRESS_HISTORY: '/mission/missions/progress-history/',
  },
  // Phase 3 planet RPG (docs/MRS - G6 Avatar API Documentation.md).
  // Shared by the member-facing game and the back-office pages.
  AVATAR: {
    GAME_STATUS: '/avatar/game-status/',
    SETTINGS: '/avatar/settings/',
    // Member — avatar
    PROFILE: '/avatar/member-avatar/profile/',
    START_JOURNEY: '/avatar/member-avatar/start-journey/',
    LEVEL_UP: '/avatar/member-avatar/level-up/',
    MY_EQUIPMENT: '/avatar/member-avatar/my-equipment/',
    EQUIP: '/avatar/member-avatar/equip/',
    UNEQUIP: '/avatar/member-avatar/unequip/',
    DISCARD: '/avatar/member-avatar/discard/',
    BATTLE_POINT_HISTORY: '/avatar/member-avatar/battle-point-history/',
    // Member — missions
    MY_MISSIONS: '/avatar/avatar-missions/my-missions/',
    MISSION_CLAIM: (uuid) => `/avatar/avatar-missions/${uuid}/claim/`,
    MISSION_CLAIM_HISTORY: '/avatar/avatar-missions/claim-history/',
    // Member — challenge
    CHALLENGE_STATUS: '/avatar/member-challenge/status/',
    CHALLENGE_ATTACK: '/avatar/member-challenge/attack/',
    CHALLENGE_OPEN_BOX: '/avatar/member-challenge/open-box/',
    CHALLENGE_MY_BOXES: '/avatar/member-challenge/my-boxes/',
    CHALLENGE_BATTLE_HISTORY: '/avatar/member-challenge/battle-history/',
    // Back office — fixed catalogs (GET + PUT/PATCH only, no create/archive)
    EQUIPMENT_ITEMS: '/avatar/equipment-items/',
    EQUIPMENT_ITEM: (uuid) => `/avatar/equipment-items/${uuid}/`,
    BOSSES: '/avatar/bosses/',
    BOSS: (uuid) => `/avatar/bosses/${uuid}/`,
    // Back office — avatar missions (full CRUD + archive)
    MISSIONS: '/avatar/avatar-missions/',
    MISSION: (uuid) => `/avatar/avatar-missions/${uuid}/`,
    MISSION_ARCHIVE: (uuid) => `/avatar/avatar-missions/${uuid}/archive/`,
    // Back office — mystery box items (full CRUD + archive)
    MYSTERY_BOX_ITEMS: '/avatar/mystery-box-items/',
    MYSTERY_BOX_ITEM: (uuid) => `/avatar/mystery-box-items/${uuid}/`,
    MYSTERY_BOX_ITEM_ARCHIVE: (uuid) => `/avatar/mystery-box-items/${uuid}/archive/`,
    MYSTERY_BOX_PROBABILITY_TOTAL: '/avatar/mystery-box-items/probability-total/'
  },
  ADMIN: {
    // Previous admin login API:
    // LOGIN: '/login/admin-access-token/',
    LOGIN: '/login/admin-login/',
    LOGIN_COMPLETE: '/login/admin-login/complete/',
    LOGOUT: '/login/logout/',
    REFRESH_TOKEN: '/login/refresh-token/',
    VERIFY_TOKEN: '/login/verify-token/',
    USERS: '/admins/users/',
    USER_SINGLE: (uuid) => `/admins/users/${uuid}/`,
    LOGIN_REQUESTS: '/admins/login-requests/',
    LOGIN_REQUEST_APPROVE: (uuid) => `/admins/login-requests/${uuid}/approve/`,
    LOGIN_REQUEST_REJECT: (uuid) => `/admins/login-requests/${uuid}/reject/`,
    ACTIVITY_LOG: '/admins/activity-log/',
    PERMISSIONS: '/admins/permissions/',
    ROLES: '/admins/roles/',
    ROLE_SINGLE: (uuid) => `/admins/roles/${uuid}/`,
    ROLE_ARCHIVE: (uuid) => `/admins/roles/${uuid}/archive/`,
    VIP_TIERS: '/member/vip-tier/',
    VIP_TIER: (uuid) => `/member/vip-tier/${uuid}/`,
    ARCHIVE_VIP_TIER: (uuid) => `/member/vip-tier/${uuid}/archive/`,
    LUCKY_SPIN_ITEMS: '/lucky-spin/lucky-spin-items/',
    LUCKY_SPIN_ITEM: (uuid) => `/lucky-spin/lucky-spin-items/${uuid}/`,
    ARCHIVE_LUCKY_SPIN_ITEM: (uuid) => `/lucky-spin/lucky-spin-items/${uuid}/archive/`,
    LUCKY_SPIN_SEQUENCES: '/lucky-spin/lucky-spin-sequences/',
    LUCKY_SPIN_SEQUENCE: (uuid) => `/lucky-spin/lucky-spin-sequences/${uuid}/`,
    CHANGE_SPIN_SEQUENCES: '/lucky-spin/lucky-spin-sequences/change-spin-sequences/',
    SMASH_EGG_ITEMS: '/smash-egg/smash-egg-items/',
    SMASH_EGG_ITEM: (uuid) => `/smash-egg/smash-egg-items/${uuid}/`,
    ARCHIVE_SMASH_EGG_ITEM: (uuid) => `/smash-egg/smash-egg-items/${uuid}/archive/`,
    SMASH_EGG_SEQUENCES: '/smash-egg/smash-sequences/',
    SMASH_EGG_SEQUENCE: (uuid) => `/smash-egg/smash-sequences/${uuid}/`,
    CHANGE_SMASH_EGG_SEQUENCES: '/smash-egg/smash-sequences/change-smash-sequences/',
    SMASH_EGG_SETTINGS: '/smash-egg/smash-egg-settings/',
    MEMBERS: '/member/members/',
    TOKEN_REPORT: '/member/token-report/',
    REWARD_REPORT: '/member/reward-report/',
    MEMBER_LIST: '/member/member-list/',
    MEMBER_LIST_SINGLE: (uuid) => `/member/member-list/${uuid}/`,
    MEMBER_DEPOSIT: (uuid) => `/member/${uuid}/member-deposit/`,
    REDEMPTION_ITEMS: '/redemption/redemption-items/',
    REDEMPTION_SETTINGS: '/redemption/settings/',
    REDEMPTION_ITEM: (uuid) => `/redemption/redemption-items/${uuid}/`,
    ARCHIVE_REDEMPTION_ITEM: (uuid) => `/redemption/redemption-items/${uuid}/archive/`,
    REDEEM_LINKS: '/redemption/redeem-links/',
    REDEEM_LINK: (uuid) => `/redemption/redeem-links/${uuid}/`,
    REDEEM_LINK_ARCHIVE: (uuid) => `/redemption/redeem-links/${uuid}/archive/`,
    REDEEM_LINK_HISTORY: (uuid) => `/redemption/redeem-links/${uuid}/history/`,
    REDEEM_LINK_KPI: '/redemption/dashboard/kpi/',
    CHECKIN_SETTINGS: '/settings/checkin-settings/',
    BANNERS: '/settings/banners/',
    BANNER: (uuid) => `/settings/banners/${uuid}/`,
    ARCHIVE_BANNER: (uuid) => `/settings/banners/${uuid}/archive/`,
    MEMBER_REPORT_DAILY: '/member/member-report/daily/',
    MEMBER_REPORT_MONTHLY: '/member/member-report/monthly/',
    MEMBER_REPORT_YEARLY: '/member/member-report/yearly/',
    STATION_LIST: '/front-view/station-list/',
    REDEMPTION_TIERS: '/redemption/redemption-tier/',
    REDEMPTION_TIER_SINGLE: (uuid) => `/redemption/redemption-tier/${uuid}/`,
    ARCHIVE_REDEMPTION_TIER: (uuid) => `/redemption/redemption-tier/${uuid}/archive/`,
    CHECKIN_TIER: '/settings/check-in-tier/',
    WALLET_VIP: '/third-party/wallet-vip/',
    WALLET_VIP_SINGLE: (uuid) => `/third-party/wallet-vip/${uuid}/`,
    WALLET_VIP_ARCHIVE: (uuid) => `/third-party/wallet-vip/${uuid}/archive/`,
    FLOATING_MENU: '/third-party/floating-menu/',
    FLOATING_MENU_SINGLE: (uuid) => `/third-party/floating-menu/${uuid}/`,
    FLOATING_MENU_ARCHIVE: (uuid) => `/third-party/floating-menu/${uuid}/archive/`,
    FLOATING_MENU_ROOT_ICON: '/third-party/floating-menu-root-icon/',
    FRAMES: '/third-party/frame/',
    FRAME_SINGLE: (uuid) => `/third-party/frame/${uuid}/`,
    FRAME_ARCHIVE: (uuid) => `/third-party/frame/${uuid}/archive/`,
    PENALTY_KICK_SETTINGS: '/penalty-kick/penalty-kick-settings/',
    PENALTY_KICK_ITEMS: '/penalty-kick/penalty-kick-items/',
    PENALTY_KICK_ITEM: (uuid) => `/penalty-kick/penalty-kick-items/${uuid}/`,
    PENALTY_KICK_ITEM_ARCHIVE: (uuid) => `/penalty-kick/penalty-kick-items/${uuid}/archive/`,
    PENALTY_KICK_SEQUENCES: '/penalty-kick/kick-sequences/',
    PENALTY_KICK_SEQUENCE: (uuid) => `/penalty-kick/kick-sequences/${uuid}/`,
    PENALTY_KICK_SEQUENCE_REORDER: '/penalty-kick/kick-sequences/change-kick-sequences/',
    AVAILABLE_PROMOTIONS: '/settings/available-promotions/',
    PROMOTIONS: '/settings/promotions/',
    PROMOTIONS_BY_STATION: (stationUuid) => `/settings/promotions/get-by-station/${stationUuid}/`,
    MISSION_SETTINGS: '/mission/settings/'
  },
  USAGE_REPORT: {
    SUMMARY: '/usage-report/summary/',
    GAMES: '/usage-report/games/',
    RETENTION: '/usage-report/games/retention/',
    INSIGHTS: '/usage-report/insights/',
  },
  EXTERNAL: {
    SPECIAL_CODE: '/third-party/special-codes/',
    WALLET_VIP_TIERS: (specialCode) => `/third-party/station-wallet-vip/${specialCode}/`,
    FLOATING_MENUS: (specialCode) => `/third-party/station-floating-menu/${specialCode}/`
  },
  WORLDCUP_USER: {
    COUNTRY_LIST: '/worldcup/country-list/',
    MATCH_COUNTRY_LIST: '/worldcup/match-country-list/',
    INFO: '/worldcup/info/',
    BANNER_LIST: '/worldcup/banner-list/',
    PRIZE_POOL: '/worldcup/prize-pool/',
    PRIZE_POOL_SINGLE: (uuid) => `/worldcup/prize-pool/${uuid}/`,
    LEADERBOARD_COUNTRIES: '/worldcup/leaderboard/countries/',
    LEADERBOARD_PLAYERS: '/worldcup/leaderboard/players/',
    LEADERBOARD_TOP_PER_COUNTRY: '/worldcup/leaderboard/top-per-country/',
    MATCH_LIST: '/worldcup/match-list/',
    MATCH_LIST_SINGLE: (uuid) => `/worldcup/match-list/${uuid}/`,
    PROFILE: (uuid) => `/worldcup/${uuid}/profile/`,
    CHOOSE_COUNTRY: (uuid) => `/worldcup/${uuid}/choose-country/`,
    PREDICT: (uuid) => `/worldcup/${uuid}/predict/`,
    PREDICTIONS: (uuid) => `/worldcup/${uuid}/predictions/`,
    MATCH_PREDICTIONS: (uuid) => `/worldcup/${uuid}/match-predictions/`,
    PREDICTION_STATUS: (uuid) => `/worldcup/${uuid}/prediction-status/`,
    MY_PREDICTION: (memberUuid, matchUuid) => `/worldcup/${memberUuid}/matches/${matchUuid}/my-prediction/`,
  },
  WORLDCUP_ADMIN: {
    SETTINGS: '/worldcup/settings/',
    BANNERS: '/worldcup/banners/',
    BANNER: (uuid) => `/worldcup/banners/${uuid}/`,
    BANNER_ARCHIVE: (uuid) => `/worldcup/banners/${uuid}/archive/`,
    REWARD_ITEMS: '/worldcup/reward-items/',
    REWARD_ITEM: (uuid) => `/worldcup/reward-items/${uuid}/`,
    REWARD_ITEM_ARCHIVE: (uuid) => `/worldcup/reward-items/${uuid}/archive/`,
    MATCHES: '/worldcup/matches/',
    MATCH: (uuid) => `/worldcup/matches/${uuid}/`,
    MATCH_ARCHIVE: (uuid) => `/worldcup/matches/${uuid}/archive/`,
    MATCH_SETTLE: (uuid) => `/worldcup/matches/${uuid}/settle/`,
    DUMMY_PLAYERS: '/worldcup/dummy-players/',
    DUMMY_PLAYER: (uuid) => `/worldcup/dummy-players/${uuid}/`,
    DUMMY_PLAYER_ARCHIVE: (uuid) => `/worldcup/dummy-players/${uuid}/archive/`,
    DUMMY_COUNTRIES: '/worldcup/dummy-countries/',
    DUMMY_COUNTRY: (uuid) => `/worldcup/dummy-countries/${uuid}/`,
    DUMMY_COUNTRY_ARCHIVE: (uuid) => `/worldcup/dummy-countries/${uuid}/archive/`,
    RANKING_REALTIME: '/worldcup/ranking/realtime/',
    DASHBOARD_KPI: '/worldcup/dashboard/kpi/',
  },
  // Unified Leaderboard API (Deposit / Withdraw / Referral).
  // Info & Campaign are shared endpoints selected by ?type= (1/2/3);
  // Status is a single global open/closed flag. Reward items and fake data
  // are per-board paths. See postman/leaderboard.md.
  LEADERBOARD: {
    INFO: '/leaderboard/info/',
    INFO_SINGLE: (uuid) => `/leaderboard/info/${uuid}/`,
    INFO_ARCHIVE: (uuid) => `/leaderboard/info/${uuid}/archive/`,
    STATUS: '/leaderboard/status/',
    CAMPAIGN: '/leaderboard/campaign/',
    CAMPAIGN_SINGLE: (uuid) => `/leaderboard/campaign/${uuid}/`,
    CAMPAIGN_ARCHIVE: (uuid) => `/leaderboard/campaign/${uuid}/archive/`,

    DEPOSIT_REWARD_ITEMS: '/leaderboard/deposit-reward-items/',
    DEPOSIT_REWARD_ITEM: (uuid) => `/leaderboard/deposit-reward-items/${uuid}/`,
    DEPOSIT_REWARD_ITEM_ARCHIVE: (uuid) => `/leaderboard/deposit-reward-items/${uuid}/archive/`,
    DEPOSIT_FAKE_DATA: '/leaderboard/deposit-fake-data/',
    DEPOSIT_FAKE_DATA_SINGLE: (uuid) => `/leaderboard/deposit-fake-data/${uuid}/`,
    DEPOSIT_FAKE_DATA_ARCHIVE: (uuid) => `/leaderboard/deposit-fake-data/${uuid}/archive/`,

    WITHDRAW_REWARD_ITEMS: '/leaderboard/withdraw-reward-items/',
    WITHDRAW_REWARD_ITEM: (uuid) => `/leaderboard/withdraw-reward-items/${uuid}/`,
    WITHDRAW_REWARD_ITEM_ARCHIVE: (uuid) => `/leaderboard/withdraw-reward-items/${uuid}/archive/`,
    WITHDRAW_FAKE_DATA: '/leaderboard/withdraw-fake-data/',
    WITHDRAW_FAKE_DATA_SINGLE: (uuid) => `/leaderboard/withdraw-fake-data/${uuid}/`,
    WITHDRAW_FAKE_DATA_ARCHIVE: (uuid) => `/leaderboard/withdraw-fake-data/${uuid}/archive/`,

    REFERRAL_REWARD_ITEMS: '/leaderboard/referral-reward-items/',
    REFERRAL_REWARD_ITEM: (uuid) => `/leaderboard/referral-reward-items/${uuid}/`,
    REFERRAL_REWARD_ITEM_ARCHIVE: (uuid) => `/leaderboard/referral-reward-items/${uuid}/archive/`,
    REFERRAL_FAKE_DATA: '/leaderboard/referral-fake-data/',
    REFERRAL_FAKE_DATA_SINGLE: (uuid) => `/leaderboard/referral-fake-data/${uuid}/`,
    REFERRAL_FAKE_DATA_ARCHIVE: (uuid) => `/leaderboard/referral-fake-data/${uuid}/archive/`,

    GENERATE_RANKING: '/leaderboard/generate-ranking/',
    REAL_RANKING: '/leaderboard/real-ranking/',
    EXCLUSIONS: '/leaderboard/exclusions/',
    EXCLUSION_ARCHIVE: (uuid) => `/leaderboard/exclusions/${uuid}/archive/`,

    PUBLIC_INFO: '/leaderboard/public/info/',
    PUBLIC_STATUS: '/leaderboard/public/status/',
    PUBLIC_CAMPAIGN: '/leaderboard/public/campaign/',
    PUBLIC_DEPOSIT_RANKING: '/leaderboard/public/deposit-ranking/',
    PUBLIC_WITHDRAW_RANKING: '/leaderboard/public/withdraw-ranking/',
    PUBLIC_REFERRAL_RANKING: '/leaderboard/public/referral-ranking/',

    // Turnover (postman/turnover.md) — shaped differently from the trio above:
    // no info/campaign/exclusions/generate-ranking, own payout schedule + logs.
    PUBLIC_TURNOVER_RANKING: '/leaderboard/public/turnover-ranking/',
    TURNOVER_MEMBER_RANK: (uuid) => `/leaderboard/turnover/member-rank/${uuid}/`,
    // Combined My Rank for all four boards in one call (deposit/withdraw are
    // from the latest generated snapshot; turnover is computed live).
    MEMBER_RANK_ALL: (uuid) => `/leaderboard/member-rank/${uuid}/`,
    TURNOVER_REWARD_ITEMS: '/leaderboard/turnover-reward-items/',
    TURNOVER_REWARD_ITEM: (uuid) => `/leaderboard/turnover-reward-items/${uuid}/`,
    TURNOVER_REWARD_ITEM_ARCHIVE: (uuid) => `/leaderboard/turnover-reward-items/${uuid}/archive/`,
    TURNOVER_FAKE_DATA: '/leaderboard/turnover-fake-data/',
    TURNOVER_FAKE_DATA_SINGLE: (uuid) => `/leaderboard/turnover-fake-data/${uuid}/`,
    TURNOVER_FAKE_DATA_ARCHIVE: (uuid) => `/leaderboard/turnover-fake-data/${uuid}/archive/`,
    TURNOVER_ADMIN_RANKING: '/leaderboard/turnover/admin-ranking/',
    TURNOVER_PAYOUT_SCHEDULE: '/leaderboard/turnover/payout-schedule/',
    TURNOVER_SETTLE_PAYOUTS: '/leaderboard/turnover/settle-payouts/',
    TURNOVER_PAYOUT_LOGS: '/leaderboard/turnover-payout-logs/',
  },
  CRM: {
    // User Access Panel
    USERS: '/admins/users/',
    USER_SINGLE: (uuid) => `/admins/users/${uuid}/`,
    LOGIN_REQUESTS: '/admins/login-requests/',
    LOGIN_REQUEST_APPROVE: (uuid) => `/admins/login-requests/${uuid}/approve/`,
    LOGIN_REQUEST_REJECT: (uuid) => `/admins/login-requests/${uuid}/reject/`,
    ACTIVITY_LOG: '/admins/activity-log/',
    PERMISSIONS: '/admins/permissions/',
    ROLES: '/admins/roles/',
    ROLE_SINGLE: (uuid) => `/admins/roles/${uuid}/`,
    ROLE_ARCHIVE: (uuid) => `/admins/roles/${uuid}/archive/`,
    // Member Profile
    MEMBERS: '/crm-members/members/',
    MEMBER_SINGLE: (uuid) => `/crm-members/members/${uuid}/`,
    MEMBER_REFRESH: (uuid) => `/crm-members/${uuid}/refresh/`,
    MEMBER_UPDATE_DATA: (uuid) => `/crm-members/${uuid}/update-data/`,
    // Retention Alert System
    PRIORITY_SUMMARY: '/crm-members/priority-summary/',
    REFRESH_MEMBERS: '/crm-members/refresh-members/',
    // Error Transaction Management
    ERROR_TRANSACTIONS: '/crm-members/error-transactions/',
    ERROR_TRANSACTION_CLEAR: '/crm-members/error-transactions/clear-error/',
    ERROR_TRANSACTION_DELETE: '/crm-members/error-transactions/delete-transaction/',
    // Retention Profile
    RETENTION_SUMMARY: (adminUuid) => `/crm-members/retention-summary/${adminUuid}/`,
    // Old path returned 404 on staging:
    // RETENTION_MEMBERS: '/crm-members/retention-profile/',
    RETENTION_MEMBERS: '/crm-members/retention-members/',
    ADMIN_MEMBERS: (adminUuid) => `/crm-members/${adminUuid}/admin-members/`,
    FOLLOW_UPS: '/crm-members/follow-up/',
    MEMBER_ASSIGN_TO_PIC: (memberUuid) => `/crm-members/members/${memberUuid}/assign-to-pic/`,
    MEMBER_FOLLOW_UP: (memberUuid) => `/crm-members/members/${memberUuid}/follow-up/`,
    MEMBER_ALERT: (memberUuid) => `/crm-members/members/${memberUuid}/alert/`,
    MEMBER_SEND_BONUS: (memberUuid) => `/crm-members/members/${memberUuid}/send-bonus/`,
    GIVE_TOKENS: '/crm-members/give-tokens/',
    GIVE_BATTLE_POINTS: '/crm-members/give-battle-points/',
    // Dashboard
    DASHBOARD_SUMMARY: '/crm-admins/dashboard-summary/',
    DASHBOARD_BREAKDOWN: '/crm-admins/dashboard-breakdown/',
    DASHBOARD_DETAILS: '/crm-admins/dashboard-details/',
    NOTIFICATIONS: '/crm-admins/notifications/',
    NOTIFICATION_MARK_READ: (uuid) => `/crm-admins/notifications/${uuid}/mark-as-read/`,
    // Member Assignment
    ASSIGNMENTS: '/crm-admins/assignments/',
    ASSIGNMENT_SINGLE: (uuid) => `/crm-admins/assignments/${uuid}/`,
    ASSIGNMENT_IMPORT_MEMBERS: (uuid) => `/crm-admins/assignments/${uuid}/import-members/`,
    ASSIGNMENT_RETENTION_TARGET: (adminUuid) => `/crm-admins/assignments/${adminUuid}/retention-target/`,
    ASSIGNMENT_SET_TARGET: '/crm-admins/assignments/set-target/',
    // CRM MRS VIP Tier aliases.
    // Old CRM-specific paths returned 404 on staging:
    // CRM_VIP_TIERS: '/crm-admins/vip-tier/',
    // CRM_VIP_TIER_SINGLE: (uuid) => `/crm-admins/vip-tier/${uuid}/`,
    // CRM_VIP_TIER_ARCHIVE: (uuid) => `/crm-admins/vip-tier/${uuid}/archive/`
    CRM_VIP_TIERS: '/member/vip-tier/',
    CRM_VIP_TIER_SINGLE: (uuid) => `/member/vip-tier/${uuid}/`,
    CRM_VIP_TIER_ARCHIVE: (uuid) => `/member/vip-tier/${uuid}/archive/`
  }
};
