export const LEADERBOARD_TYPES = {
  DEPOSIT: 'deposit',
  REFERRER: 'referrer',
  WITHDRAWAL: 'withdrawal',
};

export const LEADERBOARD_CONFIG = {
  [LEADERBOARD_TYPES.DEPOSIT]: {
    label: 'Deposit',
    title: 'Deposit Leaderboard',
    valueLabel: 'Deposit',
    tableValueHeader: 'TOTAL DEPOSIT',
    color: '#ff8c00',
    colorLight: '#ffb965',
    colorMuted: '#ddc1ae',
    tableBorder: '#564334',
    rowBorder: '#715029',
    headerBg: 'rgba(255,140,0,0.2)',
    rank1Bg: '#ff8c00',
    rank1Shadow: 'rgba(255,140,0,0.5)',
    rank1Border: '#ff8c00',
    rank2Color: '#4a8eff',
    rank2Bg: '#4a8eff',
    rank2Border: '#4a8eff',
    rank2TextDark: '#00285b',
    rank2PrizeColor: '#adc7ff',
    rank3Color: '#ff8494',
    rank3Bg: '#ff8494',
    rank3Border: '#ff8494',
    rank3TextDark: '#810029',
    rank3PrizeColor: '#ffb2ba',
    icon: '/assets/leaderboard/wallet-icon.svg',
    showCountdown: true,
    showPrizeColumn: true,
  },
  [LEADERBOARD_TYPES.REFERRER]: {
    label: 'Referrer',
    title: 'Referrer Leaderboard',
    valueLabel: 'New Members',
    tableValueHeader: 'NEW MEMBER',
    color: '#007bff',
    colorLight: '#65aaff',
    colorMuted: '#ddc1ae',
    tableBorder: '#344056',
    rowBorder: '#496b8e',
    headerBg: 'rgba(0,123,255,0.2)',
    rank1Bg: '#007bff',
    rank1Shadow: 'rgba(0,123,255,0.5)',
    rank1Border: '#007bff',
    rank2Color: '#ffba4a',
    rank2Bg: '#ffba4a',
    rank2Border: '#ffba4a',
    rank2TextDark: '#583600',
    rank2PrizeColor: '#ffba4a',
    rank3Color: '#ff8494',
    rank3Bg: '#ff8494',
    rank3Border: '#ff8494',
    rank3TextDark: '#810029',
    rank3PrizeColor: '#ffb2ba',
    icon: '/assets/leaderboard/referrer-icon.svg',
    showCountdown: false,
    showPrizeColumn: true,
  },
  [LEADERBOARD_TYPES.WITHDRAWAL]: {
    label: 'Withdrawal',
    title: 'Withdrawal',
    valueLabel: 'Withdrawal',
    tableValueHeader: 'TOTAL WITHDRAWAL',
    color: '#ae00ff',
    colorLight: '#c850ff',
    colorMuted: '#ddc1ae',
    tableBorder: '#4e3456',
    rowBorder: '#75498e',
    headerBg: 'rgba(174,0,255,0.2)',
    rank1Bg: '#ae00ff',
    rank1Shadow: 'rgba(174,0,255,0.5)',
    rank1Border: '#ae00ff',
    rank2Color: '#ffba4a',
    rank2Bg: '#ffba4a',
    rank2Border: '#ffba4a',
    rank2TextDark: '#583600',
    rank2PrizeColor: '#ffba4a',
    rank3Color: '#ff8494',
    rank3Bg: '#ff8494',
    rank3Border: '#ff8494',
    rank3TextDark: '#810029',
    rank3PrizeColor: '#ffb2ba',
    icon: '/assets/leaderboard/withdrawal-icon.svg',
    showCountdown: false,
    showPrizeColumn: false,
  },
};
