export const VIP_DETAILS_ASSETS = {
  titleBanner: "/assets/vip-details/vip-details-title.png",
  vipChain: "/assets/vip-details/vip-chain.png",
  privilegesBg: {
    bronze: "/assets/vip-details/bronze-privileges-bg.png",
    silver: "/assets/vip-details/silver-privileges-bgv2.png",
    gold: "/assets/vip-details/gold-privileges-bg.png",
    platinum: "/assets/vip-details/platinum-privileges-bg.png",
    diamond: "/assets/vip-details/diamond-privileges-bg.png",
  },
  starIcon: "/assets/vip-details/star-icon.png",
  checkIcon: "/assets/vip-details/check-icon.png",
  badges: {
    bronze: "/assets/ranks/rank/Bronze.png",
    silver: "/assets/ranks/rank/Silver.png",
    gold: "/assets/ranks/rank/Gold.png",
    platinum: "/assets/ranks/rank/Platinum.png",
    diamond: "/assets/ranks/rank/Diamond.png",
    emerald: "/assets/ranks/rank/Emarald.png",
    ruby: "/assets/ranks/rank/Ruby.png",
    sapphire: "/assets/ranks/rank/Sapphire.png",
    amethyst: "/assets/ranks/rank/Amethyst.png",
  },
  rankIcons: {
    1: "/assets/ranks/vip-level-1.png",
    2: "/assets/ranks/vip-level-2.png",
    3: "/assets/ranks/vip-level-3.png",
    4: "/assets/ranks/vip-level-4.png",
    5: "/assets/ranks/vip-level-5.png",
    6: "/assets/ranks/vip-level-6.png",
    7: "/assets/ranks/vip-level-7.png",
    8: "/assets/ranks/vip-level-8.png",
    9: "/assets/ranks/vip-level-9.png",
  }
};
