export const VIP_DETAILS_ASSETS = {
  titleBanner: "/assets/vip-details/vip-details-title.webp",
  vipChain: "/assets/vip-details/vip-chain.webp",
  privilegesBg: {
    bronze: "/assets/vip-details/bronze-privileges-bg.webp",
    silver: "/assets/vip-details/silver-privileges-bgv2.webp",
    gold: "/assets/vip-details/gold-privileges-bg.webp",
    platinum: "/assets/vip-details/platinum-privileges-bg.webp",
    diamond: "/assets/vip-details/diamond-privileges-bg.webp",
  },
  starIcon: "/assets/vip-details/star-icon.webp",
  checkIcon: "/assets/vip-details/check-icon.webp",
  badges: {
    bronze: "/assets/ranks/rank/Bronze.webp",
    silver: "/assets/ranks/rank/Silver.webp",
    gold: "/assets/ranks/rank/Gold.webp",
    platinum: "/assets/ranks/rank/Platinum.webp",
    diamond: "/assets/ranks/rank/Diamond.webp",
    emerald: "/assets/ranks/rank/Emarald.webp",
    ruby: "/assets/ranks/rank/Ruby.webp",
    sapphire: "/assets/ranks/rank/Sapphire.webp",
    amethyst: "/assets/ranks/rank/Amethyst.webp",
  },
  rankIcons: {
    1: "/assets/ranks/vip-level-1.webp",
    2: "/assets/ranks/vip-level-2.webp",
    3: "/assets/ranks/vip-level-3.webp",
    4: "/assets/ranks/vip-level-4.webp",
    5: "/assets/ranks/vip-level-5.webp",
    6: "/assets/ranks/vip-level-6.webp",
    7: "/assets/ranks/vip-level-7.webp",
    8: "/assets/ranks/vip-level-8.webp",
    9: "/assets/ranks/vip-level-9.webp",
  }
};
