import { PHASE4_ASSETS } from "../../config/phase4";

export const SPIN_ASSETS = {
  background: "/assets/lucky-spin/lucky-spin-grid/spin-bg.webp",
  itemGold: "/assets/lucky-spin/lucky-spin-grid/spin-item-gold.webp",
  itemGreen: "/assets/lucky-spin/lucky-spin-grid/spin-item-green.webp",
  itemFrame: "/assets/lucky-spin/lucky-spin-grid/spin-item-frame.webp",
  itemEmptyGold: "/assets/lucky-spin/lucky-spin-grid/2.webp",
  itemEmptyGreen: "/assets/lucky-spin/lucky-spin-grid/1.webp",
  prize1: "/assets/lucky-spin/lucky-spin-grid/spin-prize-1.webp",
  prize2: "/assets/lucky-spin/lucky-spin-grid/spin-prize-2.webp",
  prize3: "/assets/lucky-spin/lucky-spin-grid/spin-prize-3.webp",
  centerButton: "/assets/lucky-spin/lucky-spin-grid/spin-center.webp",
  centerButtonStop: "/assets/lucky-spin/lucky-spin-grid/spn-stop.webp",
  buttonBackground: "/assets/lucky-spin/buttons/button.webp",
  scrollBackground: "/assets/lucky-spin/rewards/scroll-bg.webp",
  coinFrame: "/assets/lucky-spin/rewards/coin-frame.webp",
  coin1: "/assets/lucky-spin/rewards/coin-1.webp",
  coin2: "/assets/lucky-spin/rewards/coin-2.webp",
  rewardsListBackground: "/assets/lucky-spin/rewards/rewards-list-bg.png",
  winningListBackground: "/assets/lucky-spin/winning-list/background.webp",
  coinIcon: PHASE4_ASSETS.token,
  battlePointIcon: PHASE4_ASSETS.battlePoint,
  bulletIcon: "/assets/lucky-spin/winning-list/bullet-icon.webp",
};
