"""Regenerate each theme's Boss War frame specs from the artwork itself.

The hand-entered slice numbers were rough estimates from the export agents.
This measures the real ornament thickness per file and emits warFrame() calls
carrying the art's pixel size, so the border scales uniformly (no squashing).
"""
import os
import re
import numpy as np
from PIL import Image

ROOT = r"D:/Things I Need/IDX Projects/Kreatech/mrs-g6/"
PUB = ROOT + "public/assets/themes/"

THEMES = {
    "acebet77": ("Acebet77RpgSkin.jsx", "ACEBET_ASSETS"),
    "ubetclub": ("UbetclubRpgSkin.jsx", "UBET_ASSETS"),
    "ep369": ("Ep369RpgSkin.jsx", "EP369_ASSETS"),
    "kgame99": ("Kgame99RpgSkin.jsx", "KGAME99_ASSETS"),
    "lv918": ("Lv918RpgSkin.jsx", "LV918_ASSETS"),
    "n1gang": ("N1gangRpgSkin.jsx", "N1GANG_ASSETS"),
}
# skin key -> (assets key, reference box)
SPECS = {
    "card": ("cardFrame", (358, 160)),
    "statCard": ("statCard", (358, 96)),
    "table": ("tableFrame", (358, 440)),
    "row": ("rowFrame", (358, 52)),
    "plaque": ("plaque", (358, 213)),
}


def detail(im):
    a = np.asarray(im.convert("RGBA")).astype(float)
    al = a[..., 3] / 255.0
    lum = (a[..., 0] * .299 + a[..., 1] * .587 + a[..., 2] * .114) * al
    d = np.abs(np.gradient(lum, axis=1)) + np.abs(np.gradient(lum, axis=0))
    return np.where(al < 0.75, max(d.max(), 1.0), d)


def scan(prof, limit, thr, run):
    for i in range(min(limit, len(prof) - run)):
        if np.all(prof[i:i + run] < thr):
            return i
    return 0


def measure(path):
    im = Image.open(path)
    d = detail(im)
    h, w = d.shape
    rb = d[int(h * .42):int(h * .58), :].mean(axis=0)
    cb = d[:, int(w * .42):int(w * .58)].mean(axis=1)
    core = d[int(h * .4):int(h * .6), int(w * .4):int(w * .6)]
    thr = max(core.mean() * 2.2 + 1.0, np.percentile(d, 55))
    rw_, rh_ = max(6, w // 40), max(6, h // 40)
    t = scan(cb, int(h * .45), thr, rh_)
    b = scan(cb[::-1], int(h * .45), thr, rh_)
    l = scan(rb, int(w * .45), thr, rw_)
    r = scan(rb[::-1], int(w * .45), thr, rw_)
    f = lambda v, dim: round(100 * v / dim, 1)
    return (w, h, max(f(t, h), 2.0), max(f(r, w), 2.0), max(f(b, h), 2.0), max(f(l, w), 2.0))


def longest_run(mask):
    best = (0, 0, 0)
    i, n = 0, len(mask)
    while i < n:
        if mask[i]:
            j = i
            while j < n and mask[j]:
                j += 1
            if j - i > best[0]:
                best = (j - i, i, j)
            i = j
        else:
            i += 1
    return best[1], best[2]


def flat_run(prof):
    """Longest featureless stretch of a detail profile — a frame's interior."""
    thr = np.percentile(prof, 40) + max(prof.mean() * .35, 1.5)
    return longest_run(prof < thr)


def measure_timer(path):
    """Timer plaque: natural aspect, the countdown's window, and where the
    pill itself sits (the crown some plaques hang above it is not the pill)."""
    im = Image.open(path)
    d = detail(im)
    h, w = d.shape
    l, r = flat_run(d[int(h * .44):int(h * .56), :].mean(axis=0))
    # Probe verticals on the window's right third, clear of the crown/shield
    # ornament several plaques hang off the top-centre of the border.
    t, b = flat_run(d[:, int(l + (r - l) * .62):int(l + (r - l) * .92)].mean(axis=1))
    al = np.asarray(im.convert("RGBA"))[..., 3] / 255.0
    rows = np.where(al[:, int(w * .68):int(w * .82)].mean(axis=1) > .6)[0]
    f = lambda v, dim: round(100 * v / dim, 1)
    return (
        round(w / h, 3),
        [f(l, w), f(r, w), f(t, h), f(b, h)],
        [f(rows[0], h), f(rows[-1] + 1, h)],
    )


def asset_file(theme, key):
    """Resolve ASSETS.war.<key> to a real file under public/."""
    src = open(ROOT + f"app/components/themes/{theme}/assets.js", encoding="utf-8").read()
    m = re.search(r"^  war: \{(.*?)^  \},", src, re.S | re.M)
    if not m:
        return None
    blk = m.group(1)
    mm = re.search(rf"^\s*{key}: `\$\{{BASE\}}/war/([^`]+)`", blk, re.M)
    if not mm:
        return None
    p = PUB + theme + "/war/" + mm.group(1)
    return p if os.path.exists(p) else None


# Keys this script owns. Anything else in a theme's `war` block is a decision
# a person made (ink, the baked CTA band) and is preserved.
# bossFrame stays authored: its opening is measured by a separate pass.
MEASURED_KEYS = ("timerAspect", "timerWindow", "timerBody", "titleInset",
                 "card", "statCard", "table", "row", "plaque")

HEADER = """// GENERATED by tools/gen_skins.py — do not edit.
// Every value here is measured off this theme's own artwork under
// public/assets/themes/{theme}/war/. Re-run the script when the art changes.

import {{ warFrame }} from "../../rpg/rpgSkin";
import {{ {const} }} from "./assets";

export const WAR_FRAMES = {{
"""

for theme, (fname, const) in THEMES.items():
    lines = []
    tp = asset_file(theme, "timerPlaque")
    if tp:
        aspect, win, body = measure_timer(tp)
        lines += [
            f"  timerAspect: {aspect},",
            f"  timerWindow: [{', '.join(str(v) for v in win)}],",
            f"  timerBody: [{', '.join(str(v) for v in body)}],",
        ]
    tpl = asset_file(theme, "titlePlaque")
    if tpl:
        _, _, t, r, b, l = measure(tpl)
        lines.append(f"  titleInset: {{ top: {t}, right: {r}, bottom: {b}, left: {l} }},")
    for skin_key, (asset_key, box) in SPECS.items():
        path_ = asset_file(theme, asset_key)
        if not path_:
            continue
        w, h, t, r, b, l = measure(path_)
        lines.append(
            f"  {skin_key}: warFrame({const}.war.{asset_key}, {t}, {r}, {b}, {l}, "
            f"[{box[0]}, {box[1]}], {{ art: [{w}, {h}] }}),"
        )

    out = ROOT + f"app/components/themes/{theme}/warFrames.generated.js"
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(HEADER.format(theme=theme, const=const) + "\n".join(lines) + "\n};\n")
    print(f"{theme}: warFrames.generated.js — {len(lines)} measured values")

    # Prune the measured keys out of the authored skin and spread them in, so a
    # rerun can never revert a hand-made decision (and never churns the file).
    skin_path = ROOT + f"app/components/themes/{theme}/{fname}"
    src = open(skin_path, encoding="utf-8").read()
    m = re.search(r"^  war: \{\n(.*?)^  \},$", src, re.S | re.M)
    if not m:
        print(f"   {theme}: no war block found"); continue
    drop = re.compile(r"^    (?:%s):" % "|".join(MEASURED_KEYS))
    kept = [ln for ln in m.group(1).split("\n") if ln.strip() and not drop.match(ln)]
    body = "\n".join(["  war: {", "    ...WAR_FRAMES,"] + kept + ["  },"])
    src = src[:m.start()] + body + src[m.end():]
    if "warFrames.generated" not in src:
        src = src.replace(
            'import { THEME_IDS } from "../../../config/themes";',
            'import { THEME_IDS } from "../../../config/themes";\n'
            'import { WAR_FRAMES } from "./warFrames.generated";', 1)
    # warFrame is only referenced from the generated module now.
    if "warFrame(" not in src:
        src = src.replace(", warFrame }", " }", 1)
    open(skin_path, "w", encoding="utf-8").write(src)
    print(f"   {theme}: skin spreads WAR_FRAMES, {len(kept)} authored line(s) kept")
